### ISSUE TITLE
Strange behavior using the script on Debian 12

### ISSUE THREAD

**Issue by PedroBuffon** [nmlynch94/com.jagexlauncher.JagexLauncher#17]
I`m trying to install the launcher via the script but every time i keep getting these weird numbers and letters, idk if it``s normal.

![Screenshot_20231228_213228](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/assets/105023308/c9695c4c-372d-4256-a041-5bb0ec307081)

**Comment by nmlynch94** [comment]
@PedroBuffon i believe this is due to the shell passing along formatting characters to bash when I pipe the stdout of that curl command. You should still have the game in your app menu as long as it didn’t error out. I haven’t figured out a way to stop it from happening, but it doesn’t break the installation script.

**Comment by PedroBuffon** [comment]
Thanks for the fast response, i waited for the script to finish and it worked like a charm.
